#!/usr/bin/env sh

if ! command -v libreoffice >/dev/null 2>&1; then
  notify-send -a "File Operation" "LibreOffice is not installed. Please install it to use this script."
  exit 1
fi

for file in "$@"; do
  dir=$(dirname "$file")

  if libreoffice --headless --convert-to pdf "$file" --outdir "$dir"; then
    notify-send -a "File Operation" "Conversion complete!"
  else
    notify-send -a "File Operation" "Failed to convert $file to PDF"
  fi
done
