#!/usr/bin/env sh

if ! command -v convert >/dev/null 2>&1; then
  notify-send -a "File Operation" "ImageMagick is not installed. Please install it to use this script."
  exit 1
fi

for file in "$@"; do
  dir=$(dirname "$file")
  filename=$(basename "$file")
  name="${filename%.*}"

  if convert "$file" "$dir/$name.jpg"; then
    notify-send -a "File Operation" "Conversion complete!"
  else
    notify-send -a "File Operation" "Failed to convert $file to JPG"
  fi
done
