#!/usr/bin/env sh

if ! command -v ffmpeg >/dev/null 2>&1; then
  notify-send -a "File Operation" "ffmpeg is not installed. Please install it to use this script."
  exit 1
fi

for file in "$@"; do
  dir=$(dirname "$file")
  filename=$(basename "$file")
  name="${filename%.*}"

  if ffmpeg -i "$file" "$dir/$name.mp4"; then
    notify-send -a "File Operation" "Conversion complete!"
  else
    notify-send -a "File Operation" "Failed to convert $file to MP4"
  fi
done
