#!/usr/bin/env sh

if ! command -v ffmpeg >/dev/null 2>&1; then
  notify-send -a "File Operation" "ffmpeg is not installed. Please install it to use this script."
  exit 1
fi

for file in "$@"; do
  dir=$(dirname "$file")
  filename=$(basename "$file")
  name="${filename%.*}"

  palette="$dir/$name-palette.png"
  ffmpeg -y -i "$file" -vf "fps=25,scale=800:-1:flags=lanczos,palettegen" "$palette"

  if ffmpeg -i "$file" -i "$palette" -filter_complex "fps=25,scale=800:-1:flags=lanczos[x];[x][1:v]paletteuse" "$dir/$name.gif"; then
    rm "$palette"
    notify-send -a "File Operation" "Conversion complete!"
  else
    notify-send -a "File Operation" "Failed to convert $file to GIF"
  fi
done
