#!/usr/bin/env sh

if [ -f "$HOME/.local/share/nautilus/scripts/.env" ]; then
  . "$HOME/.local/share/nautilus/scripts/.env"
else
  notify-send -a "File Operation" "No .env file found. Please create one with your API key."
  exit 1
fi

if ! command -v curl >/dev/null 2>&1; then
  notify-send -a "File Operation" "curl is not installed. Please install it to use this script."
  exit 1
fi
if ! command -v wl-copy >/dev/null 2>&1; then
  notify-send -a "File Operation" "wl-copy is not installed. Please install it to use this script."
  exit 1
fi

for file in "$@"; do
  response=$(curl -s -H "Authorization: Client-ID $IMGUR_API_KEY" -F "image=@$file" https://api.imgur.com/3/image)

  link=$(echo "$response" | grep -o '"link":"[^"]*' | cut -d'"' -f4)

  if [ -n "$link" ]; then
    echo "$link" | wl-copy
    notify-send -a "File Operation" "Upload complete!"
    xdg-open "$link"
  else
    notify-send -a "File Operation" "Failed to upload $file to Imgur"
  fi
done
