#!/usr/bin/env sh

# Source API key from .env
if [ -f "$HOME/.local/share/nautilus/scripts/.env" ]; then
  . "$HOME/.local/share/nautilus/scripts/.env"
else
  notify-send -a "File Operation" "No .env file found. Please create one with your API key."
  exit 1
fi

# Check if curl and wl-copy are installed
if ! command -v curl >/dev/null 2>&1; then
  notify-send -a "File Operation" "curl is not installed. Please install it to use this script."
  exit 1
fi
if ! command -v wl-copy >/dev/null 2>&1; then
  notify-send -a "File Operation" "wl-copy is not installed. Please install it to use this script."
  exit 1
fi

# Loop through all selected files
for file in "$@"; do
  # Read file content
  file_content=$(cat "$file")

  # Upload file to Pastebin
  response=$(curl -X POST -s \
    -d "api_dev_key=$PASTEBIN_API_KEY" \
    -d "api_option=paste" \
    --data-urlencode "api_paste_code=$file_content" \
    -d "api_paste_name=$(basename "$file")" \
    -d "api_paste_format=bash" \
    https://pastebin.com/api/api_post.php)

  # Check if upload was successful
  case "$response" in
  http*)
    # Get the raw link
    raw_link=$(echo "$response" | sed 's|pastebin.com|pastebin.com/raw|')
    echo "$raw_link" | wl-copy
    notify-send -a "File Operation" "Upload complete!"
    xdg-open "$raw_link"
    ;;
  *)
    notify-send -a "File Operation" "Failed to upload $file to Pastebin: $response"
    ;;
  esac
done
